bookclick/urls.py
from django.conf.urls import patterns, include, url
import meets.views  
from django.contrib import admin
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bookclick.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
   
    url(r'^$', RedirectView.as_view(url=reverse_lazy('bookapp-login'))),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('meets.urls')),
    url(r'^captcha/', include('captcha.urls')),
)

meets/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

import meets.views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url=reverse_lazy('home-view'))),                              
    url(r'^booking/home/$', meets.views.HomeView.as_view(), name='home-view',), 
    url(r'^booking/list/$', meets.views.ListMeetView.as_view(), name='meets-list',),
    url(r'^booking/list/(?P<year>\d{4})/(?P<month>\d{1,2})$', meets.views.DayMonthMeetView.as_view(), name='meets-month',),
    url(r'^booking/list/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})$', meets.views.DayMonthMeetView.as_view(), name='meets-day',),
    url(r'^booking/new/$', meets.views.CreateMeetView.as_view(), name='meets-new',),
    url(r'^booking/view/(?P<pk>\d+)/$', meets.views.MeetView.as_view(), name='meets-view',),
    url(r'^booking/edit/(?P<pk>\d+)/$', meets.views.UpdateMeetView.as_view(), name='meets-edit',),
    url(r'^booking/delete/(?P<pk>\d+)/$', meets.views.DeleteMeetView.as_view(), name='meets-delete',),
) 

urlpatterns += patterns('',
    url(r'^logout/$', meets.views.LogoutView.as_view(), name='bookapp-logout'),
    url(r'^login/$', meets.views.LoginView.as_view(), name='bookapp-login'),
    url(r'^password_reset/$', meets.views.PasswordResetView.as_view(), name='bookapp-password-reset'),
    url(r'^register/$', meets.views.CreateUser.as_view(), name='bookapp-register'),
)

urlpatterns += patterns('',
    url(r'^venue/list/$', meets.views.VenueViewList.as_view(), name='venue-list',),
    url(r'^venue/new/$', meets.views.VenueViewCreate.as_view(), name='venue-new',),
    url(r'^venue/view/(?P<code>\w+)/$', meets.views.VenueView.as_view(), name='venue-view',),
    url(r'^venue/edit/(?P<code>\w+)/$', meets.views.VenueViewUpdate.as_view(), name='venue-edit',),
    url(r'^venue/delete/(?P<code>\w+)/$', meets.views.VenueViewDelete.as_view(), name='venue-delete',),
)

    

meets/models.py
import datetime
import string
import random
from django.utils import timezone
from django.db import models
from django.db.models import Q

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from django import forms

# Create your models here.
class Venue(models.Model):
    venue_name = models.CharField(max_length=200, unique=True,)
    venue_capacity = models.IntegerField(max_length=200)
    code = models.SlugField(max_length=6, unique=True, editable=False) 

    def __str__(self):
        return "%s (%s)" % (self.venue_name, self.venue_capacity)
     
    def get_absolute_url(self):
        return reverse('venue-view', kwargs={'code': self.code})

    def genere(self, N):
        caracteres = string.ascii_letters + string.digits
        aleatoire = [random.choice(caracteres) for _ in range(N)]

        self.code = ''.join(aleatoire)

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.genere(6)

        super(Venue, self).save(*args, **kwargs)

    def clean(self):
        sVenue = Venue.objects.all()

        if self.pk:
            sVenue = sVenue.exclude(pk=self.pk)

        sVenue = sVenue.filter(venue_name=self.venue_name)
        if sVenue.exists():
            raise forms.ValidationError("Venue already exists.")
 


now = datetime.datetime.now()
time_change = datetime.timedelta(0,1)  

PENDING = 'Pending'
ACCEPTED = 'Accepted'
CANCELLED = 'Cancelled'

class BookMeeting(models.Model):
    
     
    STATUS_OPTIONS = (
        (PENDING, 'Pending'),
        (ACCEPTED, 'Accepted'),
        (CANCELLED, 'Cancelled'),
    )
    book_date = models.DateField('Book Date', )
    from_time = models.TimeField('Start Time')   
    to_time = models.TimeField('End Time')           
    request_by = models.CharField(max_length=200)
    purpose = models.CharField(max_length=200)
    
    create_at = models.DateTimeField('Create Date', default=now)   # now.date()
    processed_at = models.DateTimeField('Processed Date', default=now)
    book_status = models.CharField(max_length=40, choices=STATUS_OPTIONS, default=PENDING)
    venue = models.ForeignKey(Venue)  # related_name='Book Venue'
    user = models.ForeignKey(User)    # related_name='Booked by User'

    def get_absolute_url(self):
        return reverse('meets-view', kwargs={'pk': self.id})

    def get_month_url(self, year, month):
        return reverse('meets-month', kwargs={'year': year, 'month': month})

    def get_day_url(self, year, month, day):
        return reverse('meets-day', kwargs={'year': year, 'month': month, 'day': day})

    def __str__(self):
        return "%s %s %s %s (%s) (%s)" % (self.book_date, str(self.from_time), str(self.to_time), self.venue.venue_name, 
                                                                                   self.venue.venue_capacity, self.user)

    class Meta:
        ordering = ["book_date", "from_time", ]

    def get_book_set(self):
        return BookMeeting.objects

    def clean(self):
        # Don't allow draft entries to have an error.
        #print (self.pk)
        #print (self.cleaned_data["id"])
        
        if not self.book_date or self.book_date < now.date():
            raise forms.ValidationError("You haven't set a valid Book date.")
        elif not self.to_time or not self.from_time or self.to_time <= self.from_time:
            raise forms.ValidationError("You haven't set a valid Time.") 
        elif not self.user.id:
            raise forms.ValidationError("Invalid user.") 
        elif not self.venue:
            raise forms.ValidationError("You haven't set a valid Venue.") 
        
        BooksMeet = BookMeeting.objects.exclude(pk=self.pk)
        BooksMeet = BooksMeet.filter(
                            Q(book_date=self.book_date,venue=self.venue),
                            Q(book_status='Pending') | Q(book_status='Accepted')
                            )
        
        if BooksMeet.exists():
            start_time = datetime.datetime.combine(self.book_date, self.from_time)
            end_time = datetime.datetime.combine(self.book_date, self.to_time)
            start_time = start_time + time_change
            end_time = end_time - time_change
            #8<6<10 || 8<7<10
            atBooksMeet = BooksMeet.filter(
                            Q(from_time__lte=start_time,to_time__gte=start_time) |
                            Q(from_time__lte=end_time,to_time__gte=end_time)
                            )
            if atBooksMeet.exists():
                raise forms.ValidationError("Time-slot is not available.")

        for inBooksMeet in BooksMeet:
            #1<3<5<12
            if self.from_time < inBooksMeet.from_time and self.to_time >  inBooksMeet.to_time:
                raise forms.ValidationError("Time-slot is not available. Do you want to continue?")

    
    def save(self, *args, **kwargs):
        super(BookMeeting, self).save(*args, **kwargs) # Call the "real" save() method.

meets/views.py
from datetime import datetime
from datetime import date
from calendar import monthrange

from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import render_to_response, get_object_or_404

from django.http import Http404
from django.http import HttpResponseRedirect

from django.template import RequestContext

from django.contrib.auth.decorators import login_required
from django.contrib.auth import REDIRECT_FIELD_NAME, login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm


from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse, reverse_lazy

from django.conf import settings

from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect

from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView

from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
    TemplateView,
)

from meets.models import (
    Venue,
    BookMeeting,
)

from meets.forms import (
    MeetBookForm,
    VenueForm,
    PasswordChangeForm,
    UserCreationForm,
)

from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url
from django.http import HttpResponse
import json


# Create your views here.


now = datetime.now()


def logouts(request):
    logout(request)
    return redirect(reverse('bookapp-login'))

class LoggedInMixin(object):

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(request, *args, **kwargs)

class LoginView(FormView):

    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = 'registration/login.html'

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        return super(LoginView, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('home-view')

    def form_valid(self, form):
        """
        The user has provided valid credentials (this was checked in AuthenticationForm.is_valid()). So now we
        can log him in.
        """
        username = form.cleaned_data["username"] 
        password = form.cleaned_data["password"]     
        user = authenticate(username=username, password=password) 
        if user: 
            login(self.request, user) 
        #login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())

    def set_test_cookie(self):
        self.request.session.set_test_cookie()

    def check_and_delete_test_cookie(self):
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
            return True
        return False
 
    
    def get(self, request, *args, **kwargs):
        """
        Same as django.views.generic.edit.ProcessFormView.get(), but adds test cookie stuff
        """
        if request.user.is_authenticated():
            return redirect('home-view')
 
        self.set_test_cookie()
        return super(LoginView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """
        Same as django.views.generic.edit.ProcessFormView.post(), but adds test cookie stuff
        """
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            
            self.check_and_delete_test_cookie()
            return self.form_valid(form)
        else:
            self.set_test_cookie()
            return self.form_invalid(form)

class LogoutView(LoggedInMixin, TemplateView):
    
    def get(self, request, *args, **kwargs):
        logout(self.request)
        return redirect(reverse('bookapp-login'))
   
    def get_context_data(self, **kwargs):
        context = super(LogoutView, self).get_context_data(**kwargs)
        return context

class CreateUser(CreateView):

    model = User
    template_name = 'register.html' 
    form_class = UserCreationForm
    
    def form_valid(self, form):
        """
        The user has provided valid credentials (this was checked in AuthenticationForm.is_valid()). So now we
        can log him in.
        """
        print ('0c')  
        form.save()
        """ 
        if self.request.is_ajax():
            to_json_responce = dict()
            to_json_responce['status'] = 0
            to_json_responce['form_errors'] = form.errors

            to_json_responce['new_cptch_key'] = CaptchaStore.generate_key()
            to_json_responce['new_cptch_image'] = captcha_image_url(to_json_responce['new_cptch_key'])

            return HttpResponse(json.dumps(to_json_responce), content_type='application/json')
        """  
        username = form.cleaned_data["username"] 
        password2 = form.cleaned_data["password2"]    
        user = authenticate(username=username, password=password2)
        human = True 

        if user: 
            login(self.request, user)
            HttpResponseRedirect(self.get_success_url())

        return HttpResponseRedirect(reverse('bookapp-login'))

    def form_invalid(self, form):
        """
        form.save()
        if self.request.is_ajax():
            to_json_responce = dict()
            to_json_responce['status'] = 1

            to_json_responce['new_cptch_key'] = CaptchaStore.generate_key()
            to_json_responce['new_cptch_image'] = captcha_image_url(to_json_responce['new_cptch_key'])

            return HttpResponse(json.dumps(to_json_responce), content_type='application/json')
        """

    def get(self, request, *args, **kwargs):
        print ('1c')
        if request.user.is_authenticated():
            return redirect('home-view')
        return super(CreateUser, self).get(request, *args, **kwargs)

    def get_form_kwargs(self):
        print ('2c')   
        kwargs = super(CreateUser, self).get_form_kwargs()
        return kwargs

    def get_initial(self):
        print ('3c')
        initial = super(CreateUser, self).get_initial()
        return initial

    def get_success_url(self):
        print ('4c')
        return reverse('home-view')
        #return reverse('bookapp-login')

    def get_context_data(self, **kwargs):
        print ('5c')
        context = super(CreateUser, self).get_context_data(**kwargs)
        context['action'] = reverse('bookapp-register')
        return context

    def post(self, request, *args, **kwargs):
        print ('6c')
        return super(CreateUser, self).post(request, *args, **kwargs)



class PasswordResetView(LoggedInMixin, FormView):
    """
    Class based version of django.contrib.auth.views.password_reset
    """
    #form_class = PasswordResetForm
    form_class = PasswordChangeForm
    template_name = 'registration/password_change_form.html'
    
    def get_success_url(self):
        return reverse('home-view')

    def get_form(self, form_class):
        return form_class(**self.get_form_kwargs())

    def get_form_class(self):
        return self.form_class

    def get(self, request, *args, **kwargs):
        return super(PasswordResetView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        current_user = kwargs.pop('current_user', None)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        return super(PasswordResetView, self).post(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(PasswordResetView, self).get_form_kwargs()
        kwargs['current_user'] = get_object_or_404(User, username__exact = self.request.user)
        return kwargs

    
    def get_context_data(self, **kwargs):
        context = super(PasswordResetView, self).get_context_data(**kwargs)
        print ('1=')
        return context


    def form_valid(self, form):
        """
        User has entered an email address of a valid user (checked by PasswordResetForm)
        """
        form.save()
        return HttpResponseRedirect(self.get_success_url())



class ListMeetView(LoggedInMixin, ListView):

    model = BookMeeting
    template_name = 'meet_list.html'
    context_object_name = 'bookings'

    def get_success_url(self):
         
        if not request.user.is_active:
            return redirect('bookapp-login')

        return reverse('meets-list')

    def get_queryset(self):
        today = datetime.now()
        my_year = int(today.year)
        my_month = int(today.month)
        my_calendar_from_month = date(my_year, my_month, 1)
        my_calendar_to_month = date(my_year, my_month, monthrange(my_year, my_month)[1])

        return BookMeeting.objects.filter(book_date__gte=my_calendar_from_month).filter(book_date__lte=my_calendar_to_month)


    def get_context_data(self, **kwargs):
        context = super(ListMeetView, self).get_context_data(**kwargs)
        today = datetime.now()
        my_year = int(today.year)
        my_month = int(today.month)
        my_calendar_from_month = date(my_year, my_month, 1)
        my_calendar_to_month = date(my_year, my_month, monthrange(my_year, my_month)[1])
        my_previous_year = my_year
        my_previous_month = my_month - 1
        if my_previous_month == 0:
            my_previous_year = my_year - 1
            my_previous_month = 12
        my_next_year = my_year
        my_next_month = my_month + 1
        if my_next_month == 13:
            my_next_year = my_year + 1
            my_next_month = 1
        my_year_after_this = my_year + 1
        my_year_before_this = my_year - 1
        
        my_events = BookMeeting.objects.filter(book_date__gte=my_calendar_from_month).filter(book_date__lte=my_calendar_to_month)
          
        context['events_list'] = my_events
        context['month'] = my_month

meets/templates/home.html
{% extends "adm/base_site.html" %}
{% load i18n admin_static %}



{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "adm/css/dashboard.css" %}" />{% endblock %}
{% block coltype %}colMS{% endblock %}


{% block bodyclass %}dashboard{% endblock %}


{% block breadcrumbs %}
 <div class="breadcrumbs">
    <a href="{% url 'home-view' %}">{% trans 'Home' %}</a>
    </div>
{% endblock %}

{% block content %}

<div id="content-main">

       <div class="module">
        <table>
        <caption>
            <a href="{% url 'home-view' %}" class="section">
                Meeting
            </a>
        </caption>
        
            {% if user.is_superuser %}   
           <tr class="model-group">
                <th scope="row"><a href="{% url 'venue-list' %}">Venue</a></th>
                <td><a href="{% url 'venue-new' %}" class="addlink">Add</a></td>
                <td><a href="{% url 'venue-list' %}" class="changelink">Change</a></td>
            </tr>
            {% endif %}
            <tr class="model-user">
                <th scope="row"><a href="{% url 'meets-list' %}">Booking</a></th>
                <td><a href="{% url 'meets-new' %}" class="addlink">Add</a></td>
                <td><a href="{% url 'meets-list' %}" class="changelink">Change</a></td>
            </tr>
        
        </table>
        </div>

</div>

{% endblock %}

meets/templates/meet.html
{% extends "adm/base_site.html" %}
{% load i18n admin_static %}
{% block coltype %}colM{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'home-view' %}">{% trans 'Home' %}</a>
    &rsaquo; <a href="{% url 'meets-list' %}">{% trans 'Booking' %}</a>
    &rsaquo; {% trans 'View' %}
    </div>
{% endblock %}



{% block content %}

<h1>{{ 'Scheduled Meeting' }}</h1>

<fieldset class="module aligned ">

{% if booking %}
   <div class="form-row form-group">
                <label>Book Date:</label>
                <p>{{ booking.book_date|date:"l, F j, Y" }}</p> 
   </div>
   <div class="form-row form-group">
                <label>Time:</label>
                <p class='nowrap'>{{ booking.from_time|date:"H:i" }}-{{ booking.to_time|time:"H:i" }}</p>
   </div>
    <div class="form-row form-group">
                <label>Request By:</label>
                <p>{{ booking.request_by }}</p>
   </div>
   <div class="form-row form-group">
                <label>Purpose For:</label>
                <p >{{ booking.purpose }}</p>
   </div>
   <div class="form-row form-group">
                <label>Venue:</label>
                <p>{{ booking.venue.venue_name }} ({{ booking.venue.venue_capacity }})</p>
   </div>
   <div class="form-row form-group">
                <label>Book Status:</label>
                <p>{{ booking.book_status }}</p>
   </div>
{% endif %}
   
</fieldset>  
   <div class="submit-row form-group">
                         <p class="deletelink-box"><a href="{{ edit }}" class="changelink">Update</a></p>

         &nbsp;       <input id="go_contact" type="button" value="Back" class="btn btn-primary" onClick="history.go(-1)"/>     
    </div>





{% endblock %}

meets/templates/meet_delete.html
{% extends "adm/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "adm/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% block breadcrumbs %}
 <div class="breadcrumbs">
    <a href="{% url 'home-view' %}">{% trans 'Home' %}</a>
    &rsaquo; <a href="{% url 'meets-list' %}">{% trans 'Booking' %}</a>
    &rsaquo; {% trans 'Delete' %}
    </div>
{% endblock %}


{% block content %}

{% if booking %}
<h1>Delete Scheduled Meeting</h1>

<p>Are you sure you want to delete the scheduled meeting {{ booking }} ?</p>

<form action="{{ action }}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url 'meets-list' %}">No, cancel.</a>
</form>
{% endif %}

{% endblock %}

meets/templates/meet_edit.html
{% extends "adm/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}

<script type="text/javascript" src="{% static 'adm/jsi18n/' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/core.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/admin/RelatedObjectLookups.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/jquery.init.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/actions.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/calendar.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/admin/DateTimeShortcuts.js' %}"></script>

{% endblock %}


{% block coltype %}colM{% endblock %}


{% block bodyclass %}change-form{% endblock %}


{% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'home-view' %}">{% trans 'Home' %}</a>
    &rsaquo; <a href="{% url 'meets-list' %}">{% trans 'Booking' %}</a>
    &rsaquo; {% trans 'Update' %}
    </div>
{% endblock %}


{% block content %}


<h1>Update Scheduled Meeting</h1>


<form action="{{ action }}" method="post" role="form">
<fieldset class="module aligned ">
  <div class="help-block">
 {% if form.non_field_errors %}
    <ul class="errorlist">
      {% for error in form.non_field_errors %}
        <li>  {{ error }}  </li>
      {% endfor %}
    </ul>
  {% endif %}
  </div>


         
            {% for field in form.visible_fields %}
               
            <div id="div_{{ field.html_name }}"
                 class="form-row form-group{% if field.errors %} has-error{% endif %}">
                {{ field.label_tag }}
                {{ field }}
                <div class="text-muted pull-right">
                    <small>{{ field.help_text }}</small>
                </div>
                <div class="help-block">
                    {{ field.errors }}
                </div>
            </div>
              {% if field.html_name == 'book_date' %}
              <script type="text/javascript">document.getElementById("id_{{ field.html_name }}").focus();</script>
              {% endif %} 
            {% endfor %}
            
          
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
          
            
            {% comment %}  <input id="id_user" type="hidden" name="user" value={{user.id}}> {% endcomment %}            
            {% csrf_token %}
  </fieldset>            
            <div class="submit-row form-group">
                <p class="deletelink-box"><a href="{{ delet }}" class="deletelink">Delete</a></p>
                <input id="go_contact" type="button" value="Back" class="btn btn-primary" onClick="history.go(-1)"/>
                <input id="save_contact" type="submit" value="Save" class="btn btn-primary" />
            </div>
            

<script type="text/javascript">
(function($) {
    var field;
})(django.jQuery);

</script>
                  
 </form>


{% endblock %}

meets/templates/register.html
{% extends "adm/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}

<script type="text/javascript" src="{% static 'adm/jsi18n/' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/core.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/admin/RelatedObjectLookups.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/jquery.init.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/actions.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/calendar.js' %}"></script>
<script type="text/javascript" src="{% static 'adm/js/admin/DateTimeShortcuts.js' %}"></script>

{% endblock %}


{% block coltype %}colM{% endblock %}
{% block bodyclass %}change-form{% endblock %}


{% block breadcrumbs %}
    <div class="breadcrumbs">
     <a href="{% url 'bookapp-login' %}">{% trans 'Login' %}</a> 
    &rsaquo; {% trans 'Register' %}
    </div>
    </div>
{% endblock %}


{% block content %}


<h1>Registration</h1>


 <form action="{{ action }}" method="post" role="form">
<fieldset class="module aligned ">
 <div class="help-block">
 {% if form.non_field_errors %}
    <ul class="errorlist">
      {% for error in form.non_field_errors %}
        <li>  {{ error }}  </li>
      {% endfor %}
    </ul>
  {% endif %}
  </div>

     
         {% for field in form.visible_fields %}
          <div class="form-row field-{{ field.html_name }}{% if field.errors %} has-error{% endif %}">
            <div>
                <span class='nowrap' >{{ field.label_tag }} </span>
                {{ field }} 
                 
                  {% if field.html_name == 'captcha' %}
                  <a href="{% url 'bookapp-register' %}">{% trans 'Refresh' %}</a> 
                     {% comment %}
                    <button class='js-captcha-refresh' value="Refresh"></button>
                    {% endcomment %}
                  {% endif %}

                <div class="text-muted pull-right">
                    <small>{{ field.help_text }}</small>
                </div>
                <div class="help-block">
                    {{ field.errors }}
                </div>
            </div>
          </div>
          
          
           
   
         {% endfor %}
           
         
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
           
            {% comment %} <input id="id_user" type="hidden" name="user" value={{user.id}}>{% endcomment %}
                          
            {% csrf_token %}
           
 </fieldset>      

            <div class="submit-row form-group">
                <!-- <input id="go_contact" type="button" value="Back" class="btn btn-primary" onClick="history.go(-1)"/> -->
                <input id="save_contact" type="submit" value="Save" class="btn btn-primary" />
                
            </div>
            

 </form>

<script type="text/javascript">
(function($) {
    var field;
})(django.jQuery);

</script>

{% comment %}
<script type="text/javascript">
$('.js-captcha-refresh').click(function(){
    $form = $(this).parents('form');

    $.getJSON($(this).data('url'), {}, function(json) {
        // This your should update captcha image src and captcha hidden input
    });

    return false;
});
</script>
{% endcomment %}







{% endblock %}

meets/templates/venue.html
{% extends "adm/base_site.html" %}
{% load i18n admin_static %}

{% block coltype %}colM{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'home-view' %}">{% trans 'Home' %}</a>
    &rsaquo; <a href="{% url 'venue-list' %}">{% trans 'Venues' %}</a>
    &rsaquo; {% trans 'View' %}
    </div>
{% endblock %}


{% block content %}

<h1>{{ 'Scheduled Venue' }}</h1>

  
<fieldset class="module aligned ">

{% if venue %}
   <div class="form-row form-group">
                <label>Venue Name :</label>
                <p>{{ venue.venue_name }}</p> 
   </div>
    <div class="form-row form-group nowrap">
                <label>Capacity :</label>
                <p>{{ venue.venue_capacity }}</p>
   </div> 
{% endif %}
   
</fieldset>  
   <div class="submit-row form-group">
              <p class="deletelink-box"><a href="{{ edit }}" class="changelink">Update</a></p>
      &nbsp;  <input id="go_contact" type="button" value="Back" class="btn btn-primary" onClick="history.go(-1)"/>     
    </div>


{% endblock %}